pro-billing/app/projects/urls.py
from django.urls import path

from . import views

app_name = "projects"

urlpatterns = [
    path(
        "detail/<uuid:uuid>/checkout/",
        views.ProjectCheckoutView.as_view(),
        name="checkout",
    ),
    path(
        "detail/<uuid:uuid>/portal/",
        views.ProjectPortalView.as_view(),
        name="portal",
    ),
    path(
        "detail/<uuid:uuid>/terms/",
        views.ProjectTermsView.as_view(),
        name="terms",
    ),
    path(
        "detail/<uuid:uuid>/token/",
        views.ProjectTokenView.as_view(),
        name="token",
    ),
    path("create/", views.ProjectCreateView.as_view(), name="create"),
    path("", views.ProjectListView.as_view(), name="list"),
]

pro-billing/app/projects/models.py
import uuid

from django.contrib.postgres.fields import ArrayField
from django.db import models

from models import TimestampModel, UUIDModel
from forgestripe.models import StripeModel

from github import invite_username_to_repo, remove_username_from_repo
from packages.models import Package


class Project(TimestampModel, UUIDModel, StripeModel):
    name = models.SlugField(
        unique=True, max_length=255, help_text="Unique slug across all projects"
    )
    team = models.ForeignKey(
        "teams.Team", on_delete=models.CASCADE, related_name="projects"
    )
    # url?

    terms_accepted_at = models.DateTimeField(null=True, blank=True)
    terms_accepted_by = models.ForeignKey(
        "users.User", on_delete=models.SET_NULL, null=True, blank=True
    )

    packages_token = models.UUIDField(default=uuid.uuid4)

    # Person (people) who will be invited to repo for this project
    github_usernames = ArrayField(
        models.SlugField(max_length=255), blank=True, null=True
    )

    # Mostly used for the Stripe status
    status = models.CharField(max_length=255, default="")

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    @property
    def is_active(self):
        return self.status == "active"

    def sync_stripe(self):
        subscription = self.get_stripe_object()
        if subscription:
            self.status = subscription.status
        else:
            self.status = ""
        self.save()

    def invite_github_usernames(self):
        for package in Package.objects.all():
            for username in self.github_usernames:
                invite_username_to_repo(username, package.repo_full_name)

    def remove_github_usernames(self):
        for package in Package.objects.all():
            for username in self.github_usernames:
                has_other_projects = (
                    Project.objects.exclude(id=self.id)
                    .filter(status="active", github_usernames__icontains=username)
                    .exists()
                )
                if not has_other_projects:
                    remove_username_from_repo(username, package.repo_full_name)

pro-billing/app/projects/views.py
from django.conf import settings
from django.core.exceptions import PermissionDenied
from django.urls import reverse
from django.utils import timezone
from django.views import generic

import stripe
from forgestripe.views import StripeCheckoutView, StripePortalView

from views import BaseLoggedInViewMixin

from .models import Project


class ProjectQuerysetMixin:
    def get_queryset(self):
        team_ids = self.request.user.teams.values_list("id", flat=True)
        return super().get_queryset().filter(team_id__in=team_ids)


class ProjectDetailMixin(ProjectQuerysetMixin):
    model = Project
    slug_field = "uuid"
    slug_url_kwarg = "uuid"


class ProjectCreateView(BaseLoggedInViewMixin, generic.CreateView):
    model = Project
    fields = ["name"]
    html_title = "Start a new project"

    def form_valid(self, form):
        form.instance.team = self.request.user.teams.first()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("projects:terms", kwargs={"uuid": self.object.uuid})


class ProjectTokenView(BaseLoggedInViewMixin, ProjectDetailMixin, generic.DetailView):
    template_name = "projects/project_token.html"

    def get_html_title(self):
        return f"{self.object} token"

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)

        if not obj.is_active:
            raise PermissionDenied("Project is not active")

        return obj


class ProjectTermsView(BaseLoggedInViewMixin, ProjectDetailMixin, generic.UpdateView):
    fields = ["github_usernames"]
    template_name = "projects/project_terms.html"
    html_title = "License terms"

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        # For now we'll make this look like a single value field
        form.fields["github_usernames"].label = "GitHub username"
        form.fields["github_usernames"].widget.attrs["required"] = True
        form.fields[
            "github_usernames"
        ].help_text = "The user who will be invited to the private Forge repos."
        return form

    def form_valid(self, form):
        form.instance.terms_accepted_at = timezone.now()
        form.instance.terms_accepted_by = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("projects:checkout", kwargs={"uuid": self.object.uuid})


class ProjectCheckoutView(
    BaseLoggedInViewMixin, ProjectDetailMixin, StripeCheckoutView, generic.DetailView
):
    html_title = "Checkout"

    def get(self, request, *args, **kwargs):
        """Adding a get so we can redirect straight to checkout from other forms"""
        return self.get_redirect_response(request)

    def get_checkout_session_kwargs(self, request):
        project = self.get_object()

        redirect_url = request.build_absolute_uri("/")

        team = project.team
        team_stripe_info = {
            "name": team.name,
            "metadata": {"team_uuid": team.uuid},
        }

        if team.stripe_id:
            stripe.Customer.modify(team.stripe_id, **team_stripe_info)
            customer = team.stripe_id
        else:
            customer = stripe.Customer.create(**team_stripe_info)
            team.stripe_id = customer.id
            team.save()

        return {
            "customer": customer,
            "success_url": redirect_url + "?stripe=success",
            "cancel_url": redirect_url + "?stripe=cancel",
            "mode": "subscription",
            "client_reference_id": project.uuid,
            "payment_method_types": ["card"],
            "allow_promotion_codes": True,
            "line_items": [
                {
                    "price": settings.STRIPE_PRICE_ID,
                    "quantity": 1,
                }
            ],
        }


class ProjectPortalView(
    BaseLoggedInViewMixin, ProjectDetailMixin, StripePortalView, generic.DetailView
):
    html_title = "Portal"

    def get_portal_session_kwargs(self, request):
        project = self.get_object()

        return_url = request.build_absolute_uri("/")

        return {
            "customer": project.team.stripe_id,
            "return_url": return_url,
        }


class ProjectListView(BaseLoggedInViewMixin, ProjectQuerysetMixin, generic.ListView):
    model = Project
    context_object_name = "projects"
    html_title = "Projects"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if "stripe" in self.request.GET:
            context["stripe_status"] = self.request.GET["stripe"]
        return context

pro-billing/app/projects/templates/projects/project_form.html
{% extends "base.html" %}

{% block content %}

<div class="w-full max-w-lg mx-auto overflow-hidden bg-white rounded shadow">
    <div class="px-4 py-5 bg-white border-b border-gray-200 sm:px-6">
        <h1 class="text-lg font-medium leading-6 text-gray-900">Start a new project</h1>
    </div>
    <div class="p-4 sm:px-6">
        <form method="post">
            {% csrf_token %}
            <div class="flex items-start">
                <div class="flex-grow">
                    {{ form }}
                </div>
                <div class="flex flex-col">
                    <label class="text-sm">&nbsp;</label>
                    <button type="submit" class="px-4 py-2 mt-1 ml-2 text-white bg-orange-500 rounded-md hover:bg-orange-600">Create →</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

pro-billing/app/projects/templates/projects/project_keys.html
{% extends "base.html" %}

{% block content %}

<div class="w-full max-w-2xl mx-auto overflow-hidden bg-white rounded shadow">
    <div class="px-4 py-5 bg-white border-b border-gray-200 sm:px-6">
        <h1 class="text-lg font-medium leading-6 text-gray-900">Deploy key for "{{ project }}"</h1>
    </div>
    <div class="p-4 sm:px-6">
        <p class="mt-4 text-sm text-gray-800">
            This deploy key provides access to the forgepackages/forge-pro repo in Heroku and GitHub Actions.
            When you're working locally,
            git will automatically use your personal credentials.
            Using deploy keys for shared environments means you don't have to create a personal access token
            on behalf of a specific team member (which would have more permissions than it needs anyways).
        </p>
        <a class="inline-block mt-4 text-sm text-blue-500 hover:underline" href="https://www.forgepackages.com/docs/pro/">Adding your deploy key to Heroku and GitHub Actions →</a>
        <pre><code class="block p-4 mt-6 text-sm text-gray-300 bg-gray-900 rounded" style="word-break: break-all;">{{ project.pro_private_key }}</code></pre>
    </div>
</div>

{% endblock %}

pro-billing/app/projects/templates/projects/project_list.html
{% extends "base.html" %}

{% load stripe %}

{% block content %}

{% if stripe_status == "success" %}
<div class="p-4 mt-4 text-green-900 bg-green-100 border border-green-300 rounded">
    <p>
        <span class="font-medium">You're in!</span>
        Go to <a class="underline" href="https://github.com/forgepackages/forge-pro">github.com/forgepackages/forge-pro</a> to accept your invite (also in your email).
    </p>
    <p class="mt-3">
        Once you have access, you can head straight to the <a class="underline" href="https://www.forgepackages.com/docs/pro/">Forge Pro page of the docs</a>.
    </p>
    <p class="mt-3">
        If you have any questions, <a class="underline" href="https://www.forgepackages.com/contact/">contact us</a> or <a class="underline" href="https://github.com/forgepackages/forge-pro/discussions">start a discussion on GitHub</a>.
    </p>
</div>
{% endif %}

{% if projects %}
<table class="w-full mt-6 overflow-hidden divide-y divide-gray-200 rounded-md shadow">
    <thead class="bg-gray-50">
        <tr>
            <th class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">Name</th>
            <th class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">Status</th>
            <!-- <th class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">GitHub usernames</th> -->
            <!-- <th class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">License</th> -->
            <th class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">Tokens</th>
            <th class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">Subscription</th>
        </tr>
    </thead>
    <tbody class="bg-white divide-y divide-gray-200">
        {% for project in projects %}
        <tr>
            <td class="px-6 py-4 text-sm font-medium text-gray-500 whitespace-nowrap">{{ project }}</td>
            <td class="px-6 py-4 text-sm text-gray-500 whitespace-nowrap">
                {% if project.status == "active" %}
                <span class="inline-flex px-2 text-xs font-semibold leading-5 text-green-800 bg-green-100 rounded-full">{{ project.status|capfirst }}</span>
                {% elif project.status %}
                <span class="inline-flex px-2 text-xs font-semibold leading-5 text-gray-800 bg-gray-100 rounded-full">{{ project.status|capfirst }}</span>
                {{ project.status }}
                {% else %}
                -
                {% endif %}
            </td>
            <!-- <td class="px-6 py-4 text-sm text-gray-500 whitespace-nowrap">
                {% if project.github_usernames %}
                {{ project.github_usernames|join:", " }}
                {% else %}
                -
                {% endif %}
            </td> -->
            <!-- <td class="px-6 py-4 text-sm text-gray-500 whitespace-nowrap">
                {% if project.terms_accepted_at %}
                Accepted on {{ project.terms_accepted_at|date:"DATE_FORMAT" }} by {{ project.terms_accepted_by }}
                {% else %}
                -
                {% endif %}
            </td> -->
            <td class="px-6 py-4 text-sm text-gray-500 whitespace-nowrap">
                {% if project.status == 'active' %}
                <a href="{% url 'projects:token' project.uuid %}" class="flex items-center hover:underline">
                    <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 mr-1" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M18 8a6 6 0 01-7.743 5.743L10 14l-1 1-1 1H6v2H2v-4l4.257-4.257A6 6 0 1118 8zm-6-4a1 1 0 100 2 2 2 0 012 2 1 1 0 102 0 4 4 0 00-4-4z" clip-rule="evenodd" />
                    </svg>
                    View token
                </a>
                {% else %}
                -
                {% endif %}
            </td>
            <td class="px-6 py-4 text-sm text-gray-500 whitespace-nowrap">
                {% if not project.terms_accepted_at %}
                <a href="{% url 'projects:terms' project.uuid %}" class="text-orange-600 hover:underline">Accept license terms</a>
                {% elif project.stripe_id %}
                <form method="post" action="{% url 'projects:portal' project.uuid %}" class="inline">
                    {% csrf_token %}
                    <button type="submit" class="text-orange-600 hover:underline">Manage subscription</button>
                </form>
                {% else %}
                <form method="post" action="{% url 'projects:checkout' project.uuid %}">
                    {% csrf_token %}
                    <button type="submit" class="px-4 py-2 text-white bg-orange-600 rounded-md hover:bg-orange-700">Start subscription</button>
                </form>
                {% endif %}

                {% if project.stripe_id and project.status == "active" %}
                <div class="mt-1 text-xs">
                Renews {{ project.stripe_object.current_period_end|epoch_to_datetime|date:"DATE_FORMAT" }}
                </div>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div class="flex">
    <a href="{% url 'projects:create' %}" class="flex items-center px-4 py-2 mx-auto mt-8 text-gray-500 hover:underline">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="h-8 mr-2 bi bi-plus" viewBox="0 0 16 16">
            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
        </svg>
        Start a new project
    </a>
</div>
{% else %}
<div class="mt-8 text-center">
    <h1 class="text-2xl font-semibold text-gray-600">Welcome to Forge!</h1>
    <p class="mx-auto mt-4 text-gray-600 max-w-prose">
        All you need to do here is set up a subscription, which will automatically invite you to the private forgepackages/forge-pro repo on GitHub.
        Once you have access, you can head straight to the docs.
    </p>
    <a href="{% url 'projects:create' %}" class="inline-block px-4 py-2 mt-6 text-white bg-orange-600 rounded-md hover:bg-orange-700">Choose a name for your first project →</a>
</div>
{% endif %}
{% endblock %}

pro-billing/app/projects/templates/projects/project_terms.html
{% extends "base.html" %}

{% block content %}

<div class="w-full max-w-2xl mx-auto overflow-hidden bg-white rounded shadow">
    <div class="px-4 py-5 bg-white border-b border-gray-200 sm:px-6">
        <h1 class="text-lg font-medium leading-6 text-gray-900">License terms for "{{ project }}"</h1>
    </div>
    <div class="p-4 sm:px-6">
        <p class="mt-4 text-sm text-gray-800">
            Make sure you are aware of the terms.
            In short, you don't have permission to redistribute the Forge Pro code.
            If you have licensing questions or are purchasing on behalf of a team or organization, <a href="https://www.forgepackages.com/contact/" class="text-indigo-600 hover:underline">contact us</a>.
        </p>
        <div class="p-2.5 overflow-y-scroll border border-gray-200 rounded bg bg-gray-50 h-[34rem] mt-8">
        {% include "projects/license_terms.html" %}
        </div>
        <form method="post" class="mt-10">
            {% csrf_token %}
            {{ form }}

            <div class="flex items-center mt-6">
                <input id="terms_accepted" type="checkbox" required class="w-4 h-4 text-indigo-600 border-gray-300 rounded focus:ring-indigo-500">
                <label for="terms_accepted" class="ml-2 text-sm font-medium text-gray-700">I accept the license terms</label>
            </div>

            <button type="submit" class="block w-full px-4 py-2 mt-8 text-white bg-orange-500 rounded-md hover:bg-orange-600">Continue</button>
        </form>
    </div>
</div>

{% endblock %}

pro-billing/app/projects/templates/projects/project_token.html
{% extends "base.html" %}

{% block content %}

<div class="w-full max-w-4xl mx-auto overflow-hidden bg-white rounded shadow">
    <div class="px-4 py-5 bg-white border-b border-gray-200 sm:px-6">
        <h1 class="text-lg font-medium leading-6 text-gray-900">Token for "{{ project }}"</h1>
    </div>
    <div class="p-4 sm:px-6">
        <p class="mt-4 text-sm text-gray-800">
            To install private packages, use <code>https://pypi.forgepackages.com/</code> as an additional package repo.
            In Poetry for example, you can add this section to your <code>pyproject.toml</code>:
        </p>

        <pre><code class="block p-4 mt-3 text-sm text-gray-300 bg-gray-900 rounded" style="word-break: break-all;">[[tool.poetry.source]]
name = "forgepackages"
url = "https://pypi.forgepackages.com/"
</code></pre>

        <p class="mt-4 text-sm text-gray-800">
            In <span class="font-bold">development</span>, use your personal credentials to authenticate your entire machine:
        </p>
        <pre><code class="block p-4 mt-3 text-sm text-gray-300 bg-gray-900 rounded" style="word-break: break-all;">poetry config http-basic.forgepackages {{ request.user.username }} {{ request.user.packages_token }}</code></pre>

        <p class="mt-4 text-sm text-gray-800">
            In <span class="font-bold">Heroku</span>, use the project credentials:
        </p>
        <pre><code class="block p-4 mt-3 text-sm text-gray-300 bg-gray-900 rounded" style="word-break: break-all;">heroku config:set FORGEPACKAGES_AUTH="{{ project.name }}:{{ project.packages_token }}"</code></pre>

        <p class="mt-4 text-sm text-gray-800">
            In <span class="font-bold">GitHub Actions</span>, use the project credentials (saving them as "secrets" on your repo first) in <code>test.yml</code>:
        </p>
        {% verbatim %}
        <pre><code class="block p-4 mt-3 text-sm text-gray-300 bg-gray-900 rounded" style="word-break: break-all;">    # previous steps
    - name: Install dependencies
      env:
        POETRY_HTTP_BASIC_FORGEPACKAGES_USERNAME: ${{ secrets.FORGEPACKAGES_PROJECT }}
        POETRY_HTTP_BASIC_FORGEPACKAGES_PASSWORD: ${{ secrets.FORGEPACKAGES_TOKEN }}
      run: poetry install</code></pre>
        {% endverbatim %}

        <a class="inline-block mt-4 text-sm text-blue-500 hover:underline" href="https://www.forgepackages.com/docs/pro/">More information can be found in the docs →</a>
    </div>
</div>

{% endblock %}

{% block footer_scripts %}
<script src="https://unpkg.com/@dropseed/codeplus@0.6.3/dist/browser.js"></script>
<script>
window.addEventListener("load", function() {
    new Codeplus({
        copyButtonClass: "items-center flex hover:bg-gray-700 text-gray-100 rounded border border-gray-200 px-2 py-1 text-sm",
    }).render();
});
</script>
{% endblock %}